### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'

### ISSUE THREAD

**Issue by sccrthlt** [google/gin-config#9]
### Problem Definition
I receive the following error when running `import gin.tf`:
`AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'`

### Install Process
I installed `gin-config` via `pip` inside an existing Anaconda environment:
`pip install gin-config`

### Traceback
```
Python 3.6.7 |Anaconda custom (64-bit)| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym.tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gym.tf'
>>> import gin.tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\18048\AppData\Local\Continuum\anaconda3\envs\base_3_6\lib\site-packages\gin_config-0.1.3-py3.6.egg\gin\tf\__init__.py", line 20, in <module>
    from gin.tf.utils import GinConfigSaverHook
  File "C:\Users\18048\AppData\Local\Continuum\anaconda3\envs\base_3_6\lib\site-packages\gin_config-0.1.3-py3.6.egg\gin\tf\utils.py", line 34, in <module>
    config.register_file_reader(tf.io.gfile.GFile, tf.io.gfile.exists)
AttributeError: module 'tensorflow._api.v1.io' has no attribute 'gfile'
```

### Versions
```
tensorflow                1.12.0
gin-config                0.1.3               
```

Any assistance is greatly appreciated!

**Comment by tikste** [comment]
I had the same problem. It seems like, this problem has been introduced with 08e61a8f9a682d0e289a9d30734f3236b97708cc.

As a work-around I cloned gin-config

`git clone https://github.com/google/gin-config.git`

checked out the commit before

`git checkout 89e9c79d465263ce825e718d90413e2bcffadd64`

and installed from source

`python -m setup.py install`

**Comment by satyakesav** [comment]
@sccrthlt, Try pip install gin-config==0.1.1 directly. It worked for me.

**Comment by sccrthlt** [comment]
@tikste answer below worked for me!!

> I had the same problem. It seems like, this problem has been introduced with [08e61a8](https://github.com/google/gin-config/commit/08e61a8f9a682d0e289a9d30734f3236b97708cc).
> 
> As a work-around I cloned gin-config
> 
> `git clone https://github.com/google/gin-config.git`
> 
> checked out the commit before
> 
> `git checkout 89e9c79d465263ce825e718d90413e2bcffadd64`
> 
> and installed from source
> 
> `python -m setup.py install`

**Comment by satyakesav** [comment]
Which TF version are you using?

**Comment by tikste** [comment]
@satyakesav I am using tensorflow 1.12.0, non gpu version.

**Comment by sguada** [comment]
We are working in making gin-config 0.1.4 works with TF 1.12 stable.

**Comment by sguada** [comment]
Ok now we have a new gin-config 0.1.4 release, can you double check that it works for you?

**Comment by tikste** [comment]
@sguada It works for me. Thank you!

**Comment by sccrthlt** [comment]
@sguada works for me as well! Thank you!

**Comment by Gurubux** [comment]
Tensor-flow Version - **2.0.0-alpha0**

Same error occurred while running a notebook from the Tensorflow site  - [**Build a linear model with Estimators**](https://www.tensorflow.org/tutorials/estimators/linear )
<br>
Download the dataset:
```
from official.wide_deep import census_dataset
from official.wide_deep import census_main

census_dataset.download("/tmp/census_data/")
```

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-9-fa1d43ace000> in <module>()
>       2 from official.wide_deep import census_main
>       3 
> ----> 4 census_dataset.download("/tmp/census_data/")
> 
> /content/models/official/wide_deep/census_dataset.py in download(data_dir)
>      76 def download(data_dir):
>      77   """Download census data if it is not already present."""
> ---> 78   **tf.gfile.MakeDirs(data_dir)**
>      79 
>      80   training_file_path = os.path.join(data_dir, TRAINING_FILE)
> 
> **AttributeError: module 'tensorflow' has no attribute 'gfile'**
<hr>

## The document suggests the following changes in the file.
### _Should I go about making the following changes manually in the file census_dataset.py ?_
WARNING: Logging before flag parsing goes to stderr.
W0625 16:04:36.412110 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:78: The name tf.gfile.MakeDirs is deprecated. Please use **tf.io.gfile.makedirs** instead.

W0625 16:04:36.413802 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:81: The name tf.gfile.Exists is deprecated. Please use **tf.io.gfile.exists** instead.

W0625 16:04:38.253764 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:62: The name tf.gfile.Open is deprecated. Please use **tf.io.gfile.GFile** instead.

W0625 16:04:38.488776 139807458662144 deprecation_wrapper.py:119] From /tmpfs/src/temp/site/en/tutorials/estimators/models/official/wide_deep/census_dataset.py:73: The name tf.gfile.Remove is deprecated. Please use **tf.io.gfile.remove** instead.

**Comment by Ehtasha** [comment]
Tensorflow version is 1.12.0.

And I have install gin-config 0.1.4 using bellow command.

`!pip install gin-config==0.1.4`

But it is not working.

Error Statement:
module 'tensorflow._api.v1.math' has no attribute 'is_inf'.
