### ISSUE TITLE
TF2.0 compatibility?

### ISSUE THREAD

**Issue by evancasey** [google/gin-config#14]
Does this work with TF 2.0 / is compatibility on the roadmap? Great work so far on this.

**Comment by foxik** [comment]
Also interested in the answer, as I have already started using TF 2.0.

**Comment by jackd** [comment]
For anyone interested: I've got a minimally modified fork [here](https://github.com/jackd/gin-config/tree/tf2). Haven't hit any issues yet, but not heavily tested.

**Comment by sguada** [comment]
Thanks @jackd if you want to make a PR we can review it and test it.

**Comment by soCzech** [comment]
```
--> import gin.tf.external_configurables

../gin/tf/external_configurables.py in <module>
    144 # Distribution strategies.
--> 145 config.external_configurable(tf.contrib.distribute.MirroredStrategy,
    146                              module='tf.contrib.distribute')

AttributeError: module 'tensorflow' has no attribute 'contrib'
```

[gin/tf/external_configurables.py](https://github.com/google/gin-config/blob/master/gin/tf/external_configurables.py#L145) contains `tf.contrib.distribute.MirroredStrategy` from `tf.contrib.distribute` package that is not in TF2.0. 

Commenting out that line solves the problem.
