### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.random' has no attribute 'categorical'

### ISSUE THREAD

**Issue by jinPrelude** [google/gin-config#10]
### Problem Definition

I receive the following error when running `import gin.tf.external_configurables` : 
`AttributeError: module 'tensorflow._api.v1.random' has no attribute 'categorical'`

### Install Process
I installed `gin-config' via GitHub, and installed older version to avoid the error #9   : 
```
git clone https://github.com/google/gin-config.git
git checkout 89e9c79d465263ce825e718d90413e2bcffadd64
python -m setup.py install
``` 

### TraceBack

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gin.tf.external_configurables
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/Users/user-name/rl/lib/python3.6/site-packages/gin_config-0.1.2-py3.6.egg/gin/tf/external_configurables.py", line 99, in <module>
AttributeError: module 'tensorflow._api.v1.random' has no attribute 'categorical'
```

### Versions
```
tensorflow   1.12.0
gin-config   0.1.2
```

Any assistance is greatly appreciated!!

**Comment by Holt59** [comment]
I temporarily solve this by installing `tensorflow` 1.13rc0:

```
pip install tensorflow==1.13rc0
```

**Comment by jinPrelude** [comment]
@Holt59 Wow it works.. I should have tried it before opening the issue.. Thanks for your kindness!

**Comment by sguada** [comment]
Thanks @Holt59 for responding to the issue. We are working in making gin-config 0.1.4 works with TF 1.12 stable.

**Comment by sguada** [comment]
Ok now we have a new gin-config 0.1.4 release, can you double check that it works for you?

**Comment by Holt59** [comment]
@sguada Version 0.1.4 seems to be working with TF 1.12 now. Can also confirm that this seems to solve #9 together with this one. Thanks!
